CREATE TABLE PERSON (
  ID   NUMERIC AUTO_INCREMENT,
  NAME NVARCHAR2(100),
  AGE  NUMERIC
);

INSERT INTO PERSON (NAME, AGE) VALUES ('John' , 10);
INSERT INTO PERSON (NAME, AGE) VALUES ('Bill' , 20);
INSERT INTO PERSON (NAME, AGE) VALUES ('Susan', 30);
